Merged PR 73437: Fix automation pre-sync if data fields are set
## What's being changed

This fixes a regression introduced in 4.34.0 that broke the automation pre-sync for customers and guests, and failed to sync data fields for non-customer and non-guest enrolments.

- Unit tests are updated to ensure we catch these errors in future.
- `mergeFields` is rewritten for clarity and robustness.

## Why it's being changed

In ContactManager, data fields are formatted as a structured array with 'Key' and 'Value' keys. When this kind of array was used when hydrating a new SdkContact, the patch request failed with e.g.
```
dotdigital.ERROR: Enrolment failed for automation id: 3, message: server:badRequest - Bad request [[{"item":"line 1, position 92","description":"Invalid type. Expected Object but got Array. Path: `dataFields`."}]]
```
Only, we couldn't see the detail because we didn't add full exception logging for the Automation consumer - this is also fixed.

## How to review / test this change

- Configure customer, guest and abandoned cart automations
- Enable Email Capture and allow AC for non-subscribers
- Drop a guest cart, and wait for the enrolment to run
- Confirm you see a contact created in Dotdigital with the ABANDONED_PROD_NAME data field set
- Now place an order as this guest
- Confirm the guest order automation is picked up and processed as expected
- Confirm the contact is created in Dotdigital with the correct data fields
- Create a customer
- Confirm the new customer automation is picked up and processed as expected
- Confirm the guest is created in Dotdigital with the correct data fields

## Notes

The ContactManager code is now a bit repetitive. We export data, which returns a hydrated SdkContact. Then we extract its data fields, merge them with new ones, and then hydrate another new SdkContact. We're stuck a little bit here because our SDK doesn't have the methods needed to take a hydrated SdkContact and add extra DataField objects to its existing DataFieldCollection. In this PR I've only done the minimum to fix the bug.

Related work items: #337705